#!/bin/bash
cont=1
while [ $cont -le 10 ]
do
	echo "Construyendo artefacto parte $cont"
	let cont++
done
echo "Artefacto construido"
cat >primerArtefacto.html <<EOF
<html>
  <body>
    <h3>El primer artefacto creado</h3>
    <p>La tuberia que ha creado el artefacto ha sido: $GO_PIPELINE_NAME</p>
  </body>
</html>
EOF
